matches:
  - trigger: ":date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%m/%d/%Y %H:%M:%S"

  - trigger: ":timestamp"
    replace: "{{timestamp}}"
    vars:
      - name: timestamp
        type: date
        params:
          format: "%s"

  - trigger: ":doge"
    replace: "[旺柴]"

  - trigger: ":smile"
    replace: "[奸笑]"

  - trigger: ":hide"
    replace: "[捂脸]"

  - trigger: ":gua"
    replace: "[吃瓜]"

  - trigger: ":666"
    replace: "[666]"

  - trigger: ":ok"
    replace: "[好的]"
